# Count the number of pairs generated by two nested loops.
n= int(input("Enter a number: "))
count=0
for i in range(1,n+1):
    for j in range(1,n+1):
        count+=1
print(count)

# Print all pairs whose sum equals n.
n= int(input("Enter a number: "))
for i in range(1,n+1):
    for j in range(1,n+1):
        if i+j==n:
            print(f'({i},{j})')
            
# Print all pairs (i,j) where i < j.
n= int(input("Enter a number: "))
for i in range(1,n+1):
    for j in range(1,n+1):
        if i<j:
            print(f'({i},{j})')

# Print all pairs where i + j is even.
n= int(input("Enter a number: "))
for i in range(1,n+1):
    for j in range(1,n+1):
        if (i+j)%2==0:
            print(f'({i},{j})')

# Find all pairs of numbers between 1 and n whose product is n.
n= int(input("Enter a number: "))
for i in range(1,n+1):
    for j in range(1,n+1):
        if i*j==n:
            print(f'({i},{j})')